# We want to execute Reek for CICD verification step purposes. Not all instances of a smell are offenses; in the case of
# smells like FeatureEnvy, sometimes it's the opposite. We only enable detectors if we think almost all instances of a
# smell mean that the code can be refactored to be better, and that checking in the offending code requires a
# justification in those cases. If you want to detect code that offends the disabled detectors, edit the file
# temporarily.

detectors:
  UncommunicativeParameterName:
    # Delegate this check to rubocop.
    enabled: false
  TooManyStatements:
    # Delegate this check to rubocop.
    enabled: false
  TooManyMethods:
    # Delegate this check to rubocop's measuring cops.
    enabled: false
  UncommunicativeVariableName:
    # (1) Delegate this check to rubocop.
    # (2) Names can be terser if the scope of the name is short.
    enabled: false

  FeatureEnvy:
    # Supressing this smell is less important than upholding other principles.
    enabled: false
  UtilityFunction:
    # Supressing this smell is less important than upholding other principles.
    enabled: false
  DuplicateMethodCall:
    # Instances of this smell don't necessarily indicate code we are not confident in.
    enabled: false
  ControlParameter:
    # From documentation at time of writing this:
    # > Control Coupling is a kind of duplication, because the calling method already knows which path should be taken.
    #
    # For behavior impacted by external factors such as user input, the best place to decide the code path to take might
    # not be the calling method.
    enabled: false

  LongParameterList:
    exclude:
      # We decided to take on the tech debt incurred by the 4 parameters of update_evaluation_stack_based_on_token and
      # it should be refactored.
      - "SymDiffer::ExpressionTextLanguageCompiler::ExpressionTreeBuilder#update_evaluation_stack_based_on_token"
      # We decided to take on the tech debt incurred by the 4 parameters of build_command_type_stack_item and it should
      # be refactored.
      - "SymDiffer::ExpressionTextLanguageCompiler::Checkers::IdentifierTokenChecker#build_command_type_stack_item"
      - "SymDiffer::ExpressionTextLanguageCompiler::Checkers::MultiplicationTokenChecker#build_command_type_stack_item"
      - "SymDiffer::ExpressionTextLanguageCompiler::Checkers::SubtractionTokenChecker#build_command_type_stack_item"
      - "SymDiffer::ExpressionTextLanguageCompiler::Checkers::SumTokenChecker#build_command_type_stack_item"

  NilCheck:
    # Use of Nil and nil checks can be justified, although avoiding it is an improvement. Adding a justification for
    # each usage is not necessary.
    enabled: false

  DataClump:
    exclude:
      # We decided to take on the tech debt incurred by the data clump ['expression_text', 'variable'] and it should be
      # refactored.
      - "SymDiffer::DerivativeOfExpressionGetter"
      # We decided to take on the tech debt incurred by the data clump ['minuend', 'subtrahend'] and it should be
      # refactored.
      - "SymDiffer::ExpressionReduction::SubtractExpressionReducer"
      # We decided to take on the tech debt incurred by the data clump ['command_and_expresion_stack', 'index'] and it
      # should be refactored.
      - "SymDiffer::ExpressionTextLanguageCompiler::CommandAndExpressionStackReducer"

  Attribute:
    exclude:
      # A desirable alternative would be to create new ExpressionTexts with the new inner text value, if it didn't
      # imply unnecessary object allocations. #text= is offered as an alternative that doesn't involve additional
      # allocations.
      - "SymDiffer::ExpressionTextLanguageCompiler::ExpressionText#text"

  BooleanParameter:
    exclude:
      # We pass some parameters to the initializer to slightly customize the behavior of a StringifierVisitor.
      # References to those parameters only happen internally of StringifierVisitor, so for the time being this is a
      # fairly innocuous usage of boolean parameters.
      - "SymDiffer::StringifierVisitor#initialize"
      - "SymDiffer::StringifierVisitor#build_visitor"

  RepeatedConditional:
    # We decided to take on the tech debt incurred by repeated conditionals across this call for the time being.
    exclude:
      - "SymDiffer::StringifierVisitor"
